merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
	path('bands/', views.band_list, name='band-list'),
	path('bands/<int:id>/', views.band_detail, name='band-detail'),
	path('bands/add/', views.band_create, name='band-create'),
	path('bands/<int:id>/change/', views.band_change, name='band-change'),
	path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
	path('about-us/', views.about, name='about'),
	path('listings/', views.listing_list, name='listing-list'),
	path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
	path('listings/add/', views.listing_create, name='listing-create'),
	path('listings/<int:id>/change/', views.listing_change, name='listing-change'),
	path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),
	path('contact-us/', views.contact, name='contact'),
	path('', lambda request: HttpResponseRedirect('/bands/')), # redirect home on a page
	path('email-sent/', views.email_sent, name='email-sent')
]

handler404 = 'listings.views.error404'

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django import forms

# ----------- Model Band -----------
class Band(models.Model):

	# adjust display of band in admin
	def __str__(self):
		return f'{self.name}'
	
	# Create drop-down list 
	class Genre(models.TextChoices):
		HIP_HOP = 'HH'
		SYNTH_POP = 'SP'
		ALTERNATIVE_ROCK = 'AR'
		ROCK_N_ROLL = 'RR'

	name = models.fields.CharField(max_length=100)
	genre = models.fields.CharField(choices=Genre.choices, max_length=5)
	biography = models.fields.CharField(max_length=1000)
	year_formed = models.fields.IntegerField(
	validators=[MinValueValidator(1900), MaxValueValidator(2021)]
	)
	active = models.fields.BooleanField(default=True)
	official_homepage = models.fields.URLField(null=True, blank=True)

# ----------- Model Listing -----------
class Listing(models.Model):

	class Type(models.TextChoices):
		RECORDS = 'RCD'
		CLOTHING = 'CLT'
		POSTERS = 'PST'
		MISCELLANEOUS = 'MSL'

	title = models.fields.CharField(max_length=100)
	description = models.fields.CharField(max_length=1000)
	sold = models.fields.BooleanField(default=False)
	year = models.fields.IntegerField(null=True)
	type = models.fields.CharField(choices=Type.choices, max_length=5)
	# Add Foreign key to create connection with Band
	band = models.ForeignKey(Band, null=True, blank=True, on_delete=models.SET_NULL)

# ----------- Model BandForm -----------
class BandForm(forms.ModelForm):
	class Meta:
		model = Band
		# fields = '__all__'
		exclude = ('active', 'official_homepage')

# ----------- Model ListingForm -----------
class ListingForm(forms.ModelForm):
	class Meta:
		model = Listing
		# fields = '__all__'
		exclude = ('sold',)

merchex/listings/forms.py
from django import forms

class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Listing
from listings.forms import ContactUsForm
from django.core.mail import send_mail
from django.shortcuts import redirect
from listings.models import BandForm
from listings.models import ListingForm
from django.contrib import messages

# ----------- View Band -----------
def band_list(request):
	bands = Band.objects.all()
	return render(request,
		'listings/band_list.html',
        {'bands': bands})

def band_detail(request, id):
	band = Band.objects.get(id=id)
	return render(request,
		'listings/band_detail.html',
		{'band': band})

def band_create(request):
	if request.method == 'POST':
		form = BandForm( request.POST)
		if form.is_valid():
			band = form.save()
			return redirect('band-detail', band.id)
	else:
		form = BandForm()
	return render(request, 
		'listings/band_create.html',
		{'form' : form})

def band_change(request, id):
	band = Band.objects.get(id=id)
	if request.method == 'POST':
		form = BandForm(request.POST, instance=band)
		if form.is_valid():
			form.save()
			return redirect('band-detail', band.id)
	else:
		form = BandForm(instance=band) # i fill in the form with data of current band
	return render(request,
		'listings/band_change.html',
		{'form': form})

def band_delete(request, id):
	band = Band.objects.get(id=id)
	if request.method == 'POST':
		band.delete()
		messages.success(request, "Objet supprimé avec succès.")
		return redirect('band-list')
	return render(request,
		'listings/band_delete.html',
		{'band': band})

# ----------- View About -----------
def about(request):
    return render(request, 'listings/about.html')

# ----------- View Listing -----------
def listing_list(request):
	listings = Listing.objects.all()
	return render(request,
		'listings/listing_list.html',
		{'listings': listings})

def listing_detail(request, id):
	listing = Listing.objects.get(id=id)
	return render(request,
		'listings/listing_detail.html',
		{'listing': listing})

def listing_create(request):
	if request.method == 'POST':
		form = ListingForm(request.POST)
		if form.is_valid():
			listing = form.save()
			return redirect('listing-detail', listing.id)
	else:
		form = ListingForm()
	return render(request, 
		'listings/listing_create.html',
		{'form' : form})

def listing_change(request, id):
	listing = Listing.objects.get(id=id)
	if request.method == 'POST':
		form = ListingForm(request.POST, instance=listing)
		if form.is_valid():
			form.save()
			return redirect('listing-detail', listing.id)
	else:
		form = ListingForm(instance=listing) # i fill in the form with data of current band
	return render(request,
		'listings/listing_change.html',
		{'form': form})

def listing_delete(request, id):
	listing = Listing.objects.get(id=id)
	if request.method == 'POST':
		listing.delete()
		messages.success(request, "Objet supprimé avec succès.")
		return redirect('listing-list')
	return render(request,
		'listings/listing_delete.html',
		{'listing': listing})

# ----------- View Contact -----------
def contact(request):
    return render(request, 'listings/contact.html')

def contact(request):
	if (request.method == 'POST'):
		form = ContactUsForm(request.POST)
		if (form.is_valid()):
			send_mail(
				subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
				message=form.cleaned_data['message'],
				from_email=form.cleaned_data['email'],
				recipient_list=['admin@merchex.xyz'],
			)
			return redirect('email-sent')
	else:
		form = ContactUsForm()
	return render(request,
		'listings/contact.html',
		{'form': form}) 

def email_sent(request):
	return render(request, 'listings/email_sent.html')

# ----------- View error404 -----------
def error404(request, exception):
    return render(request, 'listings/404.html', status=404)

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>À propos</h1>
<p>Nous adorons merch !</p>

{% endblock %}

merchex/listings/templates/listings/band_change.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour du groupe</h1>

<h2>{{ band.name }}</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
</form>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supression du groupe</h1>

<p>Etes-vous certain de vouloir supprimer le groupe: {{ band.name }} ?</p>

<form action="" method="post">
	{% csrf_token %}
	<input type="submit" value="Supprimer">
</form>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
	<li>Genre : {{ band.get_genre_display }}</li>
	<li>Année de formation : {{ band.year_formed }}</li>
	<li>Actif : {{ band.active|yesno }}</li>
	<li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
</ul>
   
<p>{{ band.biography }}</p>

<h3>Articles associés:</h3>
<ul>
	{% for listing in band.listing_set.all %}
	<li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
	{% endfor %}
</ul>

<p><a href="{% url 'band-change' band.id %}">Modifier le groupe</a></p>

<p><a href="{% url 'band-delete' band.id %}">Supprimer le groupe</a></p>

<p><a href="{% url 'band-list' %}">Retour à tous les groupes</a></p>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<ul>
	{% for band in bands %}
	<li>
		<a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
		- <a href="{% url 'band-change' band.id %}">[modifier]</a>
		- <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
	</li>
	{% endfor %}
</ul>

<a href="{% url 'band-create' %}">Ajouter un goupe.</a>

{% endblock %}

<!-- <p>
	J'ai..
	{% if bands|length < 5 %}
		peu de
	{% elif bands|length < 10 %}
		quelques
	{% else %}
		beaucoup de
	{% endif %}
		groupes préférés.
</p> -->

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head><title>Merchex</title></head>
	<link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <body>
		{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li class="{% if message.tags %} {{ message.tags }} {% endif %}">
				{{ message }}
			</li>
		    {% endfor %}
		</ul>
		{% endif %}
		<nav>
			<a href="{% url 'band-list' %}">Groupes</a>
			<a href="{% url 'listing-list' %}">Merch</a>
			<a href="{% url 'about' %}">About us</a>
			<a href="{% url 'contact' %}">Contact</a>
		</nav>
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

<h1 class="validate">E-mail bien envoyée</h1>

<p>Merci pour votre message.</p>

<a href="{% url 'band-list' %}">Retour à l'accueil.</a>
<a href="{% url 'contact' %}">Envoyer un nouveau message.</a>

{% endblock %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Hello Django !</h1>
<p>
	J'ai..
	{% if bands|length < 5 %}
		peu de
	{% elif bands|length < 10 %}
		quelques
	{% else %}
		beaucoup de
	{% endif %}
		groupes préférés.
</p>
<p>Mes groupes préférés sont :</p>
<ul>
	{% for band in bands %}
	<li>{{ band.name }}</li>
	{% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/listing_change.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour de du produit</h1>

<h2>{{ listing.title }}</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
</form>

<a href="{% url 'listing-list' %}">Retour à tous les articles.</a>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouvel article</h1>

<form action="" method="post">
	{% csrf_token %} <!--generate token to block bad request-->
	{{ form.as_p }}
	<input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supression du produit</h1>

<p>Etes-vous certain de vouloir supprimer le produit: {{ listing.title }} ?</p>

<form action="" method="post">
	{% csrf_token %}
	<input type="submit" value="Supprimer">
</form>

<a href="{% url 'listing-list' %}">Retour à tous les articles</a>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ listing.title }}</h2>

<ul>
	<li>Type : {{ listing.get_type_display }}</li>
	<li>Année : {{ listing.year }}</li>
	<li>Vendu : {{ listing.sold|yesno }}</li>
	<li>Groupe : {{ listing.band }}</li>
</ul>
   
<p>{{ listing.description }}</p>

<p><a href="{% url 'listing-change' listing.id %}">Modifier le groupe</a></p>
<p><a href="{% url 'listing-delete' listing.id %}">Supprimer le groupe</a></p>
<p><a href="{% url 'listing-list' %}">Retour à tous les articles</a></p>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Listings</h1>
<p>Voici une liste de nos articles : </p>
<ul>
	{% for listing in listings %}
	<li>
		<a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
		- <a href="{% url 'listing-change' listing.id %}">[modifier]</a>
		- <a href="{% url 'listing-delete' listing.id %}">[supprimer]</a>
	</li>
	{% endfor %}
</ul>

<a href="{% url 'listing-create' %}">Ajouter un article.</a>

{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Listings</h1>
<p>Voici une liste de nos articles : </p>
<ul>
	{% for listing in listings %}
	<li>{{ listing.title }}</li>
	{% endfor %}
</ul>

{% endblock %}